### PR TITLE
Added dynamic reducing MaxChargeVoltage / fix all single Cell Voltages / add Float Mode 

### PR DESCRIPTION
**Pull request by Marvo2011**
Hello,

I added a function for dynamic reducing MaxChargeVoltage I used this before for my (single) SerialBattery and it works greate for MPPTs. ( https://github.com/Marvo2011/dbus-optimized-cvl , https://github.com/Louisvdw/dbus-serialbattery/issues/107#issuecomment-1149289839 , https://github.com/Louisvdw/dbus-serialbattery/issues/107#issuecomment-1318324035) 

_Set `DYNAMIC_CVL_PRECISION` to `0.01` in `settings.py` to activate **dynamic Charge Voltage Limit** (CVL)._
_Set `FLOAT_MODE` to a number in minutes in `settings.py` to activate the float mode after 100% is reached for x minutes._
_Set `FLOAT_CELL_VOLTAGE` to your cell based float voltage in `settings.py`_
_Set `BATTERY_CELL_DATA_FORMAT` to 1,2 or 3 in `settings.py` to resend the cell voltages to dbus._

- Added dynamic reducing MaxChargeVoltage
- Added Voltages Diff 
- Added Float Mode 
- Added optional reporting of cell voltages to dbus
- Added all single cell voltages #8 
- Fix Issue #9 
- Fix Issue #41

### CODE REVIEW

**Comment by Marvo2011** [comment]
https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/issues/8

**Comment by Dr-Gigavolt** [comment]
Hello and thanks for your contribution. The timing is unfortunately not optimal, I made a lot of changes in parallel that I need to commit first. I am on testing now. I've looked briefly through your commits, something I've already implemented in other way. I don't use _VeDbusItemImport_ any more, it is very resource hungry. I replaced it by _dbusmonitor_. And I already import cell voltages. Not to re-publish them (but I can add this feature), I calculate a sum of overvoltages of all cells exceeding MAX_CELL_VOLTAGE and subtract this sum from the just measured sum of all cell voltages to get new charge voltage limit. The problem is that Multis (my main energy source is AC coupled Fronius Symo having 3x higher power than the DC coupled SmartSolar) are very unprecise and I observed today exceeding of  MAX_CELL_VOLTAGE by 30...40 mV before. Tommorow I'll try to simply disable charger if MAX_CELL_VOLTAGE exceeded.

Best regards,
Anton

**Comment by Marvo2011** [comment]
Hello Anton,

No problem make your changes and I will take a look again. Can you access the cell voltages with the dbusmon? I run in trouble and only get 'None' as value. I report it back to do some logging with influxDB.

Thanks for your work 👍

**Comment by Marvo2011** [comment]
Hallo Anton,

for me my 'dynamic' mode works great, are you always interested to implement this in your actual version? When yes I would update my fork / pull request.
Bildschirmfoto 2023-05-30 um 07 49 32

I also think about to integrate a float mode. Like this:
Bildschirmfoto 2023-05-30 um 07 50 49

**Comment by chaerle** [comment]
I suggest, that you update your pull request, because it would it make easier to integrate and I think the feature is very important. I would also could be a tester before merging.

**Comment by Dr-Gigavolt** [comment]
Sorry, I have no time now, I'll have a look ASAP.

**Comment by Marvo2011** [comment]
@chaerle I think it is ready to test.

When you are at 2.4 you can simply update aggregatebatteries.py and settings.py by my fork.

**Comment by Dr-Gigavolt** [comment]
Hi @Marvo2011,
thanks again for your contribution. I looked briefly through your code. Have I understood correctly, is your modification for passive balancer? In case of active balancer there is no need of dynamic adaptation of CVL (my approach works well) as well as no need of "float". Lithium batteries don't float at all, the self discharging is negligible and the only what could float is the passive balancer. With active balancer you can balance even at lower CVL if you want to extend the battery life. About sending the cell voltages to Dbus ... what is the advantage of it? They are available from the instances of Serial battery. Re-sending just increases the bus traffic. I tried doing it with names making possible to identify to which battery the cell belongs, e.g. B2C11, but only integers are shown in the GUI.
Best regards,
Anton

**Comment by Marvo2011** [comment]
Hi @Dr-Gigavolt,
the dynamic adaptation of CVL can also helpfull with passive balancers or bad active balancers, but my use case is the DC coupled feed in with Victron MPPTs. Here the voltage can rise very fast, because Victron ignores any charge current limit to feed it with the inverter/multi into the grid. (Especially in a cloudy sky) 

Also for float mode, the dbus-serialbattery also have a float mode. I think it's safe to limit the voltage (float voltage) better than hold it over hours on it's top/max voltage. For DC coupled feed in it's better you have more available voltage range before the max cell voltage is reached and the BMS trigger an alarm / cut off.

I will make the resending off cell voltages configurable, so all users can use it as he want. I use it for monitoring, because I only read (all values of) the aggregate-batteries bus.

**Comment by Dr-Gigavolt** [comment]
Hello, now I`m back from my holiday and could review your code on the PC with two displays instead of small laptop :-). Please excuse me that it took such long time.  

(1)
battery name, cell voltage export ... very nice :-)

(2)
_if MaxCellVoltage <= MAX_CELL_VOLTAGE:
    MaxChargeVoltage = MAX_BATTERY_VOLTAGE + DYNAMIC_CVL_PRECISION                    # not there yet, charge with slightly higher voltage to get that current flowing_
	
Who cares about 10mV? And why do you attempt to force all the cells to reach the maximum allowed voltage? The balancer does not need it. I define this quantity (MAX_CELL_VOLTAGE) only to avoid peaking. I charge to CHARGE_VOLTAGE in average, the balancers keep the differencies very low.  

(3)
_if MaxCellVoltage > MAX_CELL_VOLTAGE:
    if MinCellVoltage < MAX_CELL_VOLTAGE:
        MaxChargeVoltage = Voltage + DYNAMIC_CVL_PRECISION                           # balancing, highest cell can't exceed mcv+x, lower cells can catch up_
    
Of course it can exceed. And you even don't recognize if more then one cell is peaking. When the cell(s) start(s) peaking there is no other way to stop it than to reduce CVL immediatelly. The balancer transfers homeopatic quantity of charge and needs days or weeks to finish the initial balance. This is exactly what I observed and wrote my aghoritm to manage it. My batteries contain 220 LTO cells, it was not possible to connect them all parallel to do initial balancing in this way. It can work well in your case if the balance is already more-less OK, but not in general.

I begun with MAX_CELL_VOLTAGE = 2.75, but realized quickly that it was a nonsense. Once reaching 2.5V they start to peak with almost no additionally stored energy and the balancer has no chance.     
	
(4)	
An example with my LTO cells:

Max. by the manufacturer allowed cell voltage: 2.8V ... but as written above, there is no reason to reach it, the cells are full at 2.45-2.5V. The 2.8V are necessary only in case of 10C charging. 
My current setting with 2batteries * 5P * 22S * 40Ah is as follows:

CHARGE_VOLTAGE = 2.45
MAX_CELL_VOLTAGE = 2.5
BMS balancer starts at 2.4V

If well balanced, the batteries are charged to 2.45 * 22 = 53.9V and the MAX_CELL_VOLTAGE is never reached. The balancers start at 2.4V and correct the small disbalance accumulated during one battery cycle.
If bad balanced, the sum of overvoltages (above MAX_CELL_VOLTAGE) of all cells and VOLTAGE_SET_PRECISION is subtracted from 53.9V and this new CVL is transmitted. In this way the MAX_CELL_VOLTAGE can be exceeded only for the time up to the next Dbus update.

(5)
I don't do the lead-acid algorithm bulk-absorption-float. At the beginning I tried it, but after discussion in https://github.com/Dr-Gigavolt/dbus-aggregate-batteries/issues/4 as well as a bit search, e.g.

https://sunonbattery.com/properly-charge-lifepo4-battery/
https://www.power-sonic.com/blog/how-to-charge-lithium-iron-phosphate-lifepo4-batteries/
https://www.global.toshiba/content/dam/toshiba/ww/products-solutions/battery/scib/pdf/ToshibaRechargeableBattery-en.pdf
https://www.youtube.com/watch?v=lCs9NaHgSB4

Please note, that lead-acid batteries have neither BMS nor balancer and they are resistent against overcharging. If overcharged, they produce H2 and O2, current continues to flow but the voltage does not peak. In this way, while N-1 cells are beeing overcharged and bubble, the last cell can be charged completely by the current doing electrolysis in all other. This is the absorption. When finisched, the voltage is reduced to float in order not to decompose the entire electrolyte. Lithium chemistries don't need this kind of choreography.

I removed it and I don't intend to put it back. It is much better reduce the SoC and/or DoD to extend the battery life. You will gain nothing if you reduce 3.4V down to 3.375V. 

And the Victron EES (in contrary to stand-alone MPPT and Multis) does not support bulk-absorption-float anyway. In on-grid system if you reduce the CVL from "absorption" to "float", the battery will be discharged with full DCL until the float voltage is reached and the not directly consumed power will be fed into the grid. Then the SOC will be less than 100% and your condition      

_if Soc == 100:
    if self._floatTimer < FLOAT_MODE * 60:
        self._floatTimer = self._floatTimer +1
    else:
        MaxChargeVoltage = FLOAT_CELL_VOLTAGE * NrOfCellsPerBattery
else:
    self._floatTimer = 0_
	
will reset the timer, escape the  "float" and it will start to oscillate.
	
So I propose:

- I'll implement (1) in my code when will have some time to test it.
- I'll keep only my algorithm. It is dynamic too, it runs reliably since several months and there were no issues reported. Never touch running system :-)
- Instead of "float" I have another idea: For each month in year define a reasonable CVL or SoC. E.g. 100% in winter and 70% in summer (less buffer necessary). And at the beginning of each month one full charge (up to the knee point) to reset the SoC counter. If you like and have time for it sooner than me, you can do it too, I would appreciate it. 
- If you wish to share your solution 1:1, please publish your fork and I'll put the link into my repository with comment "another approach"

Best regards,
Anton

**Comment by Dr-Gigavolt** [comment]
Hello, I've just deleted the comment because I've realized an thinking mistake about your voltage reduction. I'll look once more and write again.

**Comment by Dr-Gigavolt** [comment]
Hello, here is my feedback after correction. I've overlooked that the primary value for your calculation is the just measured battery voltage, not the initial CVL as in my case. 

(1)
battery name, cell voltage export ... very nice :-)

(2)
It is worth to test it.

_498: MAX_BATTERY_VOLTAGE = MAX_CELL_VOLTAGE * NrOfCellsPerBattery
499:
500: if MaxCellVoltage <= MAX_CELL_VOLTAGE:
501:    MaxChargeVoltage = MAX_BATTERY_VOLTAGE + DYNAMIC_CVL_PRECISION                    # not there yet, charge with slightly higher voltage to get that current flowing
502:
503: if MaxCellVoltage > MAX_CELL_VOLTAGE:
504:    if MinCellVoltage < MAX_CELL_VOLTAGE:
505:        MaxChargeVoltage = Voltage + DYNAMIC_CVL_PRECISION                           # balancing, highest cell can't exceed mcv+x, lower cells can catch up
506:    else:
507:        MaxChargeVoltage = MAX_BATTERY_VOLTAGE                                   # all cells at 100% SoC (for given maxcv), balancer has to bleed x from cells above maxcv
508:        elf._ownCharge = InstalledCapacity
509:
510: if MaxCellVoltage > MAX_CELL_VOLTAGE + DYNAMIC_CVL_PRECISION:
511:    MaxChargeVoltage = Voltage_ 

I think it is not necessary to add the 10mV above the measured battery voltage, who cares about it? It is nothing in comparison with apx. 50V or 60V. In case of Multis it would be even contra-productive. The error there is about 50mV, if added, you can get an error of 100mV in worst case. And you don't need to look onto the least full cell. The balancer will take care about it. Your algorithm is more simple than my one, but it think it can be done even simpler: 

in settings.py (example for your LFP):
_CHARGE_VOLTAGE = 3.4
MAX_CELL_VOLTAGE = 3.43
VOLTAGE_SET_PRECISION = 0.01 (or 0.06 for Multis)


BATTERY_VOLTAGE = CHARGE_VOLTAGE * NrOfCellsPerBattery

if MaxCellVoltage <= MAX_CELL_VOLTAGE:
   MaxChargeVoltage = BATTERY_VOLTAGE
else:
    MaxChargeVoltage = Voltage - VOLTAGE_SET_PRECISION                           # subtract, not add, to be sure not to set too much

if (voltage >= BATTERY_VOLTAGE) or (MaxCellVoltage >= MAX_CELL_VOLTAGE):                                 
   self._ownCharge = InstalledCapacity_

I begun with MAX_CELL_VOLTAGE = 2.75, but realized quickly that it was a nonsense. Once reaching 2.5V they start to peak with almost no additionally stored energy and the balancer has no chance.

(3)
I don't do the lead-acid algorithm bulk-absorption-float. At the beginning I tried it, but after discussion in the issue #4 as well as a bit search, e.g.

https://sunonbattery.com/properly-charge-lifepo4-battery/
https://www.power-sonic.com/blog/how-to-charge-lithium-iron-phosphate-lifepo4-batteries/
https://www.global.toshiba/content/dam/toshiba/ww/products-solutions/battery/scib/pdf/ToshibaRechargeableBattery-en.pdf
https://www.youtube.com/watch?v=lCs9NaHgSB4

I decided to get rid of it and I don't intend to put it back.

Please note, that lead-acid batteries have neither BMS nor balancer and they are resistant against overcharging. If overcharged, they produce H2 and O2, current continues to flow but the voltage does not peak. In this way, while N-1 cells are being overcharged and bubble, the last cell can be finished by the current electrolysing in all others. This is the absorption. When finished, the voltage is reduced to float in order not to decompose the entire electrolyte. Lithium chemistries don't need this kind of choreography. I have read a lot of voodoo about it, but all at least a bit scientific stuff reports that the battery life can be extended if not fully charged and/or not fully discharged. Not by fully charging and draining after. 

Additionally, the Victron EES (in contrary to stand-alone MPPT and Multis) does not support bulk-absorption-float anyway. In on-grid system if you reduce the CVL from "absorption" to "float", the battery will be discharged with full DCL until the float voltage is reached and the not directly consumed power will be fed into the grid. Then the SOC will be less than 100% and your condition

_578: _if Soc == 100:
579: if self._floatTimer < FLOAT_MODE * 60:
580: self._floatTimer = self._floatTimer +1
581: else:
582: MaxChargeVoltage = FLOAT_CELL_VOLTAGE * NrOfCellsPerBattery
583: else:
584: self.floatTimer = 0_

will reset the timer, escape the "float" and it will start to oscillate.

So I will do when find some time for it:
- implement (1) in my code when will have some time to test it.
- test (2) with my simplification.
- instead of "float" (3) I have another idea: For each month in year define a reasonable CVL or SoC. E.g. 100% in winter and 70% in summer (less buffer necessary). And at the beginning of each month one full charge (up to the knee point) to reset the SoC counter. If you like and have time for it sooner than me, you can do it too, I would appreciate it.

But if you wish to share your solution 1:1, please publish your fork and I'll put the link into my repository with comment "another approach"

Best regards,
Anton

**Comment by Marvo2011** [comment]
Hallo Anton,

many thanks for your review, for (1) and (2) please test it. :-)

To (3) I don't have read all your links yet, but I already have looked about Andy's (Offgrid Garage) videos in past. I know that the different energy is going into the grid, for my test only a few seconds and then the voltage is at FLOAT_VOLTAGE and my BMS (JBD) is still reporting 100%. So the rest comes from the roof / MPPT chargers. Andy also use the float mode in his actual config, I don't know if there is a video with the reason. ( https://off-grid-garage.com/my-settings/ )

I think that you have right and some BMS can have a problem with the SOC and can begin to oscillate. My BMS take a very long time (2h) at absorption voltage to get to 100% SOC. So I would set it a few minutes other people with has a BMS that reach fast the 100% should set it to a few hours. I think about that, what we can do better to resolve this problem.

I've already implemented your idea in a similar way in Node-Red, but lots off more complex, with actual weather and storm / thunder warnings to have a lot of energy when the grid is lost. I think that it is to complex to integrate it into the driver. The user can simply use Node-Red to do this. This is very simple and anyone has a different requirement.

Please let me know after your tests what you want to merge, then I think about if I want to publish it as a different fork.
But I think we should keep it simple and get one solution. Because of misunderstandings in forums etc.. or a different name?

Best regards

**Comment by Dr-Gigavolt** [comment]
Hi @Marvo2011 ,
yesterday I tested your code for cell voltages. I found out, that the max. of 24 cells in GUI is hard and not expand if more cells transmitted. Therefore I made only boolean: Either the format with battery and cell name to dbus only, or nothing.

About dynamic reduction - I remembered that I already tested the same as you do in older versions. It does not work with Multis properly because they are too slow. It is not sufficient to set CVL to measured voltage if cell over-voltage detected. If not reduced further by subtraction the sum of all overvoltages the voltage continues to rise. 

But even with mo code I observed oscillation apx. ±60A (despite CCL = 0) if one cell starts to peak. I have never seen it before, only ±couple of A. I have beta Venus now, will upgrade it in the evening and see.

**Comment by Marvo2011** [comment]
Hi @Dr-Gigavolt,

i think for the multis there is a MK3 bus update, which speed up the bus. 
https://community.victronenergy.com/questions/176323/venus-os-v30014-available-for-testing.html

Do you use the actual version? Also the firmware on multis?

**Comment by Dr-Gigavolt** [comment]
Yes I have MK3 and Multis updated couple of weeks ago. I think that is the problem:
https://community.victronenergy.com/questions/106290/bug-in-ess-dc-feed-in-enabled-charge-current-limit.html

I wrote the code in winder with few 100W from DC-coupled modules.

**Comment by TazerReloaded** [comment]
I think the float mode needs a lower SoC threshold to prevent oscillation. SerialBattery uses 90% as default (configurable).
On cloudy days, the battery will be discharged slightly whenever the grid load is higher than the PV yield (SoC < 100%), which would reset the timer for every cloud.
The goal of the "float" is to prevent keeping the battery at max voltage all day, which reduces cycle life. When full, the cells should be allowed to settle to a lower voltage.
A lower threshold would mean that the battery has to discharge a certain amount before being topped up again.

**Comment by Marvo2011** [comment]
@TazerReloaded I think configureable is a good idea. For me a reset a <100% is ok, because my BMS does not change it's SOC at so a small discharge. 

@Dr-Gigavolt that is no bug, with DC feed in, CCL would be ignored. Thats why I wrote the dynamic CVL option.

**Comment by Dr-Gigavolt** [comment]
Hi @TazerReloaded 
I've found already out that officially it is a feature, not bug. But I don't agree. If the current measurement is available in all Victron devices as well as in a battery, the control loop could keep I(PV) - I(feed) <= CCL.

What I'm trying now, is to find a better algorithm than bulk-absorption-float to keep the cell balanced as well as maintain a reasonable battery life. Not only keeping the battery at high voltage for longer time, but also 100% charging wears the battery out. I prefer to avoid full charge completely or do it less frequently. IMHO it is not correct to charge the battery to 100% every day, keep it for couple of minutes and discharge down to 90% into the grid. 

And even in case bulk-absorption-float in absorption in case of dynamic CVL it would oscillate, because it is exactly what I try now.

The next step I try is to disable DC feed in for the time when the dynamic CVL reduction is active.

Hi @Marvo2011 
I spent 2 evenings with reviewing your code. If I understood it correctly, I do the similar dynamic CVL reduction as well, since several months. But more conservatively, I don't just stop the increasing of battery voltage, but I subtract the already accumulated overvoltage (sum of overvoltages of all cells above  MAX_CELL_VOLTAGE) additionally.

**Comment by pos-ei-don** [comment]
I simply reduced Charge voltage to 55.6 V. This prevents the cells from a 100% Charge and all victron magic works perfekt. (feed in if allowed, Limit feed in as configure,...)

**Comment by Dr-Gigavolt** [comment]
> I simply reduced Charge voltage to 55.6 V. This prevents the cells from a 100% Charge and all victron magic works perfekt. (feed in if allowed, Limit feed in as configure,...)

I know, if simply reduced, it works. But if you match the CVL every second to avoid some cell(s) to peak, it will be unstable. It is not an normal operation, only in case of inbalance or if the normal CVL is set too high. It is a safety feature.

Now I hit the point, the DC feed in was automatically disabled, CCL re-activated and it works fine. When the cell difference falls under certain threshold, the feed-in will be re-activated.

**Comment by TazerReloaded** [comment]
I only charge to 55.2 as well, because going higher yields very little capacity but puts a lot more stress on the batteries.
I implemented the 90% threshold on my system, doing some tests right now, will let you know how it went.

Charging to a lower SoC during summer might be a sensible option, like only charging to 100% once a week to keep cells balanced, and ~80% for the rest. I only discharge to around 85-90% at night if the battery was full in the evening.

I also wrote my own ESS service because I didn't like how Victron handles things, still testing, but promising so far:
- two PID loops, one to keep the grid at setpoint, the other to keep the max battery current by constraining the grid loop
- respects the max current constraints of every BMS by adapting the PID loops, little over-currents can happen, but it won't blast 100A into the pack when one cell is approaching max voltage
- better low battery handling, no more oscillation between charging/discharging, the battery is instead slowly charged while the rest is used for grid compensation

**Comment by pos-ei-don** [comment]
How did you write your own ess? In NodeRed?

**Comment by TazerReloaded** [comment]
> How did you write your own ess? In NodeRed?

As a Python3 service, just like this driver. Still moving things around and optimizing, but I will share my code as soon as it is usable.
I tried NodeRed, very bulky and complicated. Python is way faster and has more options, so it's a better choice for complex tasks imo.

**Comment by Marvo2011** [comment]
@TazerReloaded looks good, but i think we should made `elif Soc <= 90:` configure able. Also if Soc is used as threshold or voltage.

**Comment by Dr-Gigavolt** [comment]
Hello guys,
ich would use only the voltage as trigger, SoC is not measured, only counted and therefore not reliable. And as already said, I won't implement to do it every day. I see no reason to charge to 100%, keep for some minutes and then discharge 10% into the grid.  I'd like to charge to voltage what you call Float and only every N days or even weeks charge fully, keep until the balancing is ready and the extra energy is self consumed.

**Comment by Dr-Gigavolt** [comment]
I am closing because the dynamic CVL is already there and works since several months. Instead of bulk-absorption-float I added similar process but not for every day. And I added your cell voltage transmission. Thanks for your participation.

**Comment by Marvo2011** [comment]
@Dr-Gigavolt Thanks, looks good, I will try it.

**Pull request closed without merging**
